# Generated by Django 2.0.1 on 2018-04-04 05:10

from django.db import migrations, models
import snippets.models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20180114_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='document',
            field=models.FileField(default=None, upload_to=snippets.models.get_file_name),
        ),
    ]
